#platform :ios, '10.0'
use_frameworks!

target 'EyeScope' do
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxOptional'
  pod 'Moya-Gloss/RxSwift'
  pod 'Moya/RxSwift'
  pod 'SwiftyBeaver'
  pod 'Hero'
  pod 'Dwifft'
  pod 'SnapKit', '~> 3.2.0'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
  pod 'AFNetworking', '~> 3.0.0'
  pod 'SDWebImage', '~> 4.0.0'
  pod 'SwiftyJSON'
  pod 'RxDataSources', '~> 1.0'
end
